const express = require('express');
const { Post, User } = require('../db');
const authenticateToken = require('../middleware/authMiddleware');

const router = express.Router();

// Publish new post (POST /api/posts)
router.post('/', authenticateToken, async (req, res) => {
    try {
        const { content, images } = req.body;
        const userId = req.user.userId;

        // Simple validation
        if (!content && (!images || images.length === 0)) {
            return res.status(400).json({ message: '内容不能为空' });
        }

        // Create new post
        const newPost = await Post.create({
            user_id: userId,
            content,
            images: images || [], // url array
            tags: [], // Leave empty for now, will be auto-generated by AI in the next phase
            status: 'published',
        });

        res.status(201).json({
            message: '发布成功',
            post: newPost,
        });
    } catch (error) {
        console.error('发布失败:', error);
        res.status(500).json({ message: '服务器错误' });
    }
});

// get the posts (GET /api/posts)
router.get('/', async (req, res) => {
    try {
        const posts = await Post.findAll({
            include: [
                {
                    model: User,
                    attributes: ['id', 'username', 'avatar'],
                },
            ],
            order: [['created_at', 'DESC']], // descending order by created_at
        });
        res.json(posts);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: '获取列表失败' });
    }
});

module.exports = router;
